export const ACTIONS = {
  FETCH_SERVICES: 'FETCH_SERVICES',
  FETCH_SERVICES_SUCCESS: 'FETCH_SERVICES_SUCCESS',
  FETCH_SERVICES_ERROR: 'FETCH_SERVICES_ERROR',
  
  FETCH_SERVICE_DETAILS: 'FETCH_SERVICE_DETAILS',
  FETCH_SERVICE_DETAILS_SUCCESS: 'FETCH_SERVICE_DETAILS_SUCCESS',
  FETCH_SERVICE_DETAILS_ERROR: 'FETCH_SERVICE_DETAILS_ERROR'
};